Repository unicode-org/message-format-wg, pull requests merged in 2023-07, with the labels that each got.

#400 docs: add roundtrip to glossary
  docs/glossary-and-resources.md
Labels: fast-track

#396 Add missing formatting sections
  spec/formatting.md
Labels: Agenda+

#393 Add interchange data model description + JSON Schema definition
  spec/data-model.md
Labels: data model

#431 Add Missing Selector Annotation error
  spec/formatting.md
  spec/syntax.md
Labels: syntax, Agenda+, formatting

#415 Fix `reserved-body` to use `quoted` rather than `literal`
  spec/message.abnf
  spec/syntax.md
Labels: Agenda+
