Repository unicode-org/message-format-wg, pull requests merged in 2023-11, with the labels that each got.

#510 Fix typo (extra line)
  spec/message.abnf
Labels: fast-track

#470 Design document for Open/Close Expressions
  exploration/open-close-expressions.md
Labels: requirements, syntax, design

#528 Copy user story from #524 to design doc
  exploration/overriding-extending-namespacing.md
Labels: design, fast-track, editorial

#531 Reformat `registry.dtd` to not repeat `<!ATTLIST>` & align attribute definitions
  spec/registry.dtd
Labels: registry, fast-track

#535 Update open-close design doc to accept the hash & slash alternative
  exploration/open-close-expressions.md
Labels: design, Agenda+

#536 Update decision-process.md
  docs/decision-process.md
Labels: fast-track

#544 Update affiliations
  delegates.md
Labels: documentation, organizational, fast-track
