Repository unicode-org/message-format-wg, pull requests merged in 2023-12, with the labels that each got.

#529 Implement code more introducer
  spec/message.abnf
Labels: syntax, specification

#540 Clarify that open-close elements are placeholders, not expressions
  exploration/open-close-placeholders.md
Labels: design, fast-track

#532 Define function aliases in registry, initially including `:integer`
  spec/registry.dtd
  spec/registry.md
  spec/registry.xml
Labels: registry

#463 (Design) Formatted Parts
  exploration/formatted-parts.md
Labels: design, Agenda+, formatting

#534 Refactor registry locale overrides
  spec/registry.dtd
  spec/registry.md
Labels: registry

#553 Unquoted literals as name or number
  spec/message.abnf
  spec/syntax.md
Labels: syntax, normative, specification

#550 Add status to formatted-parts design
  exploration/formatted-parts.md
Labels: design, fast-track

#554 data-model: Better represent annotations in the data model, particularly when unsupported
  spec/data-model/README.md
  spec/data-model/message.dtd
  spec/data-model/message.json
  spec/message.abnf
  spec/syntax.md
Labels: syntax, data model, specification

#471 (Design) Number Selection
  exploration/number-selection.md
Labels: design, registry

#542 (Design) Document the open questions around standalone markup
  exploration/open-close-placeholders.md
Labels: syntax, design

#545 Formatting: Don't remove unresolved options from the map passed to the function
  spec/formatting.md
Labels: specification, formatting

#567 Re-add accidentally dropped message validity condition
  spec/syntax.md
Labels: syntax, fast-track

#563 Describe registry use and conformance
  spec/registry.md
Labels: registry, normative, specification

#557 (Design) Exact Match Selector Options
  exploration/exact-match-selector-options.md
Labels: registry, normative

#541 Accept open-close design doc
  exploration/open-close-placeholders.md
Labels: design, Agenda+

#572 Implement ideographic space
  spec/message.abnf
  spec/syntax.md
Labels: syntax, normative, LDML45

#573 Remove mention of stability criteria
  spec/README.md
Labels: fast-track, LDML45

#473 Expand expression attributes proposal
  exploration/expression-attributes.md
Labels: syntax, data model, design, normative
