Repository unicode-org/message-format-wg, pull requests merged in 2023-10, with the labels that each got.

#469 Design document for variable mutability and namespacing
  exploration/variable-mutability.md
Labels: syntax, design, specification

#491 Remove the Prettier push action
  .github/workflows/prettier.yaml
  package.json
Labels: fast-track

#490 Remove numbers from the existing design proposals
  exploration/0000-design-proposal-template.md
  exploration/TEMPLATE.md
  exploration/builtin-registry-capabilities.md
  exploration/expression-attributes.md
Labels: fast-track

#494 Add 3 more beauty contestants
  exploration/beauty-contest.md
Labels: fast-track

#487 (design) Exterior whitespace handling
  exploration/pattern-exterior-whitespace.md
Labels: syntax, design

#508 Link to history in syntax-exploration-2.md
  exploration/syntax-exploration-2.md
Labels: fast-track
