Repository unicode-org/message-format-wg, pull requests merged in 2023-02, with the labels that each got.

#339 Actually omit surrogate code points
  spec/message.ebnf
Labels: syntax

#341 Rephrase non-goal 4 (Action #336)
  guidelines/goals.md
Labels: documentation, requirements, Action-Item

#354 Fix blockquote in spec/README and #introduction href in spec/syntax
  spec/README.md
  spec/syntax.md
Labels: fast-track
