Repository unicode-org/message-format-wg, pull requests merged in 2024-06, with the labels that each got.

#802 Simplify terms in function-composition-part-1 design doc
  exploration/function-composition-part-1.md
Labels: design, formatting, LDML46

#801 Fix comment about `name`
  spec/message.abnf
Labels: syntax, fast-track, editorial

#800 Use mappings for data model options and attributes
  spec/data-model/README.md
  spec/data-model/message.json
Labels: data model

#808 Docs: fix confusing formatting in `why_mf_next.md`
  docs/why_mf_next.md
Labels: documentation, fast-track, editorial

#807 Update 'Data-driven tests' design document
  exploration/data-driven-tests.md
Labels: test-suite, LDML46

#744 Fix references to English ordinal categories
  exploration/number-selection.md
Labels: design, fast-track, editorial
