Repository unicode-org/message-format-wg, pull requests merged in 2024-05, with the labels that each got.

#779 Add omitted notes to 2024-04-29 meeting notes
  meetings/2024/notes-2024-04-29.md
Labels: documentation, organizational, fast-track

#778 Validate test cases against a schema
  .github/workflows/validate_tests.yml
Labels: test-suite, LDML46

#775 Define missing definitions for variables
  spec/syntax.md
Labels: syntax, LDML46

#755 [DESIGN] Effect of selectors on placeholders
  exploration/selection-declaration.md
Labels: design, Action-Item, formatting, LDML46

#781 Simplify source bidi isolation rules
  exploration/bidi-usability.md
Labels: syntax, design, LDML46

#774 Refactor errors, adding section for Message Function Errors
  spec/README.md
  spec/errors.md
  spec/formatting.md
  spec/registry.md
Labels: registry, formatting, errors

#769 Add :test:function, :test:select, and :test:format function definitions
  test/README.md
Labels: test-suite

#743 Collapse all escape sequence rules into one
  spec/message.abnf
  spec/syntax.md
Labels: syntax, LDML46

#790 Update README.md
  README.md
Labels: documentation, fast-track, editorial

#794 Update readme with list of normative changes during TP
  README.md
Labels: documentation, fast-track, editorial, LDML46

#793 Recommend not escaping all the things
  spec/syntax.md
Labels: syntax

#792 [DESIGN] Add user stories / build-out of the expression attributes
  exploration/expression-attributes.md
Labels: syntax, design

#791 Update design docs and their status
  exploration/code-mode-introducer.md
  exploration/exact-match-selector-options.md
  exploration/quoted-literals.md
  exploration/selection-matching-options.md
  exploration/string-selection-formatting.md
  exploration/variable-mutability.md
  exploration/variants.md
Labels: documentation, organizational, design, editorial

#753 Add design doc on function composition
  exploration/function-composition-part-1.md
Labels: design, LDML46

#645 [DESIGN] dataflow for composability (#515)
  exploration/dataflow-composability.md
  exploration/dataflow1.jpg
  exploration/dataflow2.jpg
Labels: design, normative, specification, LDML46

#803 Align test schema with error spec
  test/schemas/v0/tests.schema.json
  test/tests/functions/date.json
  test/tests/functions/datetime.json
  test/tests/functions/number.json
  test/tests/functions/time.json
Labels: test-suite, LDML46
