Repository unicode-org/message-format-wg, pull requests merged in 2024-12, with the labels that each got.

#966 Update repo readme for "Final Candidate" status
  README.md
Labels: documentation, fast-track, editorial, LDML46.1

#967 Update specification and readme for "Final Candidate"
  spec/README.md
  spec/appendices.md
  spec/data-model/README.md
  spec/errors.md
  spec/formatting.md
  spec/intro.md
  spec/syntax.md
Labels: editorial, specification, LDML46.1

#971 Add namespaces to example non-default functions
  spec/errors.md
  spec/formatting.md
  spec/syntax.md
Labels: documentation, fast-track, editorial, LDML46.1

#969 In bidi default strategy, make steps consistent with each other
  spec/formatting.md
Labels: normative, Agenda+, formatting, LDML47

#973 Update goals.md to address v46.1
  docs/goals.md
Labels: documentation, fast-track, editorial
