Repository unicode-org/message-format-wg, pull requests merged in 2025-01, with the labels that each got.

#968 Clarification to default bidi strategy
  spec/formatting.md
Labels: editorial, formatting, LDML47

#981 Create notes-2025-01-13.md
  meetings/2025/notes-2025-01-13.md
Labels: organizational, fast-track

#980 Fix release name in Preview-Feedback issue template
  .github/ISSUE_TEMPLATE/tech-preview-feedback.md
Labels: fast-track

#982 Fix data model JSON Schema
  spec/data-model/message.json
Labels: data model, Agenda+

#984 Make normalization advice in `:string` normative
  spec/functions/string.md
Labels: registry, normative, LDML47

#985 Drop :currency currencyDisplay=formalSymbol option value
  spec/functions/number.md
Labels: registry, LDML47

#986 Deduplicate the section "Default Value of `select` Option"
  spec/functions/number.md
Labels: registry, fast-track, editorial

#992 Create notes-2025-01-27.md
  .gitignore
  meetings/2025/notes-2025-01-27.md
Labels: organizational, fast-track
